// <auto-generated />
using MessageService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageService.Migrations
{
    [DbContext(typeof(QuoteRepository))]
    partial class QuoteRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("MessageService.Models.BillboardQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Quote");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new { Id = 1, Author = "Winston Churchill", Quote = "Never, never, never give up" },
                        new { Id = 2, Author = "Marcus Tullius Cicero", Quote = "While there''s life, there''s hope" },
                        new { Id = 3, Author = "Anonymous", Quote = "Failure is success in progress" },
                        new { Id = 4, Author = "Vincent Lombardi", Quote = "Success demands singleness of purpose" },
                        new { Id = 5, Author = "Lord Herbert", Quote = "The shortest answer is doing" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
